### ISSUE TITLE
Сборка на Linux

### ISSUE THREAD

**Issue by imzhukov** [RapidScada/scada-v6#1]
Добрый день.

Попытался собраться на Ubuntu. Получил ругань:

```
/usr/share/dotnet/sdk/3.1.201/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: не найдены ссылочные сборки для .NETFramework,Version=v4.7.2. Чтобы устранить эту проблему, установите пакет разработчика (пакет SDK или пакет нацеливания) для этой версии платформы или перенацельте приложение. Пакеты разработчика для платформы .NET Framework можно скачать на странице https://aka.ms/msbuild/developerpacks. [/mnt/58A44760A447402C/code/scada-v6/ScadaServer/ScadaServer/ScadaServerSvc/ScadaServerSvc.csproj]
AppDirs.cs(109,22): error CS0103: Имя "ScadaUtils" не существует в текущем контексте. [/mnt/58A44760A447402C/code/scada-v6/ScadaServer/ScadaServer/ScadaServerCommon/ScadaServerCommon.csproj]
    Предупреждений: 2
    Ошибок: 2

```
Ждём, когда 5.0.0 выйдет из статуса beta?)

**Comment by 2mik** [comment]
Hi,

The developers use Visual Studio 2017 for building Rapid SCADA. I have no experience how to build it on Ubuntu. May be you should build for .NET Core 2.1. 

> Ждём, когда 5.0.0 выйдет из статуса beta?)
The current stable version is 5.8.0. Talking about v6, it depends on many factors.

**Comment by 2mik** [comment]
If you find a way how build the source on Ubuntu, please share.

**Comment by imzhukov** [comment]
Current stable release .NET Core - 3.1
My version you can see from this message `/usr/share/dotnet/sdk/3.1.201...`

Are you use something features from .NETFramework,Version=v4.7.2?

**Comment by 2mik** [comment]
Some projects in this repo use .NET 4.x. Check the project files,

**Comment by 2mik** [comment]
Currently there are no applications in this repository that really work. Just stubs.
