### ISSUE TITLE
Возможный race condition в ModArcPostgreSql.Logic

### ISSUE THREAD

**Issue by fortnum** [RapidScada/scada-v6#10]
Добрый день! При наполнении очереди в `PostgreCAL.WriteData` производится `lock` по `pointQueue.SyncRoot`:

https://github.com/RapidScada/scada-v6/blob/b468050a6c4820a720591d41848510c06bdcd968/ScadaServer/OpenModules/ModArcPostgreSql.Logic/PostgreCAL.cs#L250-L257

В самом `PointQueue` этот `SyncRoot` есть `return this`:

https://github.com/RapidScada/scada-v6/blob/b468050a6c4820a720591d41848510c06bdcd968/ScadaServer/OpenModules/ModArcPostgreSql.Logic/PointQueue.cs#L97-L103

В дальнейшем вызове `pointQueue.EnqueueWithoutLock` блокировка уже не производится.

А вот в `PostgreCAL.Execute` -> `PointQueue.InsertPoints`, при изъятии из очереди, `lock` берется уже по приватной `dataQueue`:

https://github.com/RapidScada/scada-v6/blob/b468050a6c4820a720591d41848510c06bdcd968/ScadaServer/OpenModules/ModArcPostgreSql.Logic/PointQueue.cs#L158-L164

То есть блокировки, по сути, не происходит, если конечно не ошибаюсь.

**Comment by 2mik** [comment]
Добрый день!
Скорее всего, ошибка в коде.
Исправлено в коммите https://github.com/RapidScada/scada-v6/commit/92f673c008e358e657161d10481d7ee7b904cd34
Спасибо
