### ISSUE TITLE
Question - When Debugging program fails because directories are not created

### ISSUE THREAD

**Issue by luis-cortina** [RapidScada/scada-v6#11]
When debugging the ScadaServerApp, it always fails because non of the default directories are created. Is there a trick to make this work other than changing the code? How do you debug this locally?

Thanks in advance...
![image](https://user-images.githubusercontent.com/25346332/177857999-9717565b-c1e6-4a9d-80b3-cbca17b6eb0b.png)

**Comment by 2mik** [comment]
I suggest the following:
1. Install Rapid SCADA 6 and make sure that it works.
2. Build ScadaServerWkr in Debug configuration.
3. Copy dlls built by yourself to the Rapid SCADA installation directory.
4. Run the service. It will prompt to run Visual Studio to debug.
