### ISSUE TITLE
SQL Scripts for PostgreSqlStorage

### ISSUE THREAD

**Issue by luis-cortina** [RapidScada/scada-v6#12]
DO you have the sql files needed to create this database tables? I'm trying to update the config into a postgres db but I dont want to create all this tables manually.
https://github.com/RapidScada/scada-v6/blob/master/Database/ConfigBase/scada_6.0.png

Thanks in advance.

Luis

**Comment by 2mik** [comment]
First,
https://github.com/RapidScada/scada-v6/tree/master/Database/Storage/sql
Second,
You need to upload configuration by the Administrator app using PostgreSQL extension. Ask on https://forum.rapidscada.org/ if more details are needed.
