### ISSUE TITLE
the schedule of v6

### ISSUE THREAD

**Issue by masterchen** [RapidScada/scada-v6#2]
good project!  what's the birthday of the v6 project ,lol

**Comment by 2mik** [comment]
Hope to release v6 beta in 2021.
Thanks

**Comment by masterchen** [comment]
@2mik  i am always watching on this project,  i cann't wait to try it, if you want me do some test please let me know.

**Comment by 2mik** [comment]
Help in testing will be appreciated. I will notify the users on [the forum](https://forum.rapidscada.org/)
The beta version will be released on Linux first. Do you use Linux?

**Comment by masterchen** [comment]
@2mik  good ,  i have a cloud computer which os is ubuntu, it should be ok for testing
