### ISSUE TITLE
ScadaSchemeEditor source code is not open source？

### ISSUE THREAD

**Issue by Zjyyy** [RapidScada/scada-v6#31]
May I ask if this tool is not open source？I did not find ScadaSchemeEditor in the code repository for scada-v6.
I wonder how I can add more custom components to ScadaSchemeEditor.

**Comment by 2mik** [comment]
Currently we use ScadaSchemeEditor from version 5.
Check the source code of the existing scheme components as examples. In case of additional questions about creating components, please ask on https://forum.rapidscada.org/

**Comment by Zjyyy** [comment]
> Currently we use ScadaSchemeEditor from version 5. Check the source code of the existing scheme components as examples. In case of additional questions about creating components, please ask on https://forum.rapidscada.org/

Thanks very much！
