### ISSUE TITLE
run this project

### ISSUE THREAD

**Issue by q383186554** [RapidScada/scada-v6#4]
dear author:
      i am foucusing on this project. i clone this project and run it for test. there is no config file in this project .could you upload it into this project. i want to test it. thanks a lot.
     i am a web developer .i hope i can do somethong for this project.

**Comment by 2mik** [comment]
Hello,
Please register the support forum https://forum.rapidscada.org/ , create a new topic and provide more info which config file do you need. We provide support via the forum.
