### ISSUE TITLE
LangPack

### ISSUE THREAD

**Issue by q383186554** [RapidScada/scada-v6#6]
Hi,
    I am going to translate langpack into Chinese while V6 is ready.

https://github.com/q383186554/RapidScadaV6-LangPack.git

**Comment by 2mik** [comment]
Hi,
It's wonderful! I will let you know when the phrases become almost stable.

**Comment by q383186554** [comment]
create_object.sql need to be update  haha ~

**Comment by q383186554** [comment]
\i 01_create_database.sql
\i 02_create_objects.sql
\i 03_schema.sql
\i 04_app.sql
\i 05_app_config.sql
\i 06_app_storage.sql
\i 07_view_file.sql
\i inserts.sql

**Comment by 2mik** [comment]
Could you clarify the question?

**Comment by q383186554** [comment]
In scada v6 create_object.sql

**Comment by 2mik** [comment]
yes

**Comment by 2mik** [comment]
Hi,
Probably, the v6 is ready enough for translation. There is a useful solution to automate the process: https://forum.rapidscada.org/?topic=xml-content-translator-for-scada-6
Thank you.
