### ISSUE TITLE
ConnectionRequired set to false, but DrvCnlBasic try to connect

### ISSUE THREAD

**Issue by McFly2017** [RapidScada/scada-v6#66]
Hi,
   I want to use the channel option config,but I don't need the default connection. So I Set ConnectionRequired = false and set  channel config. When I start ScadaCommService, DrvCnlBasic try to connect to the client which I set.
   Do you have some suggest for this solution?  Thank you very much

**Comment by 2mik** [comment]
Hi,
If a communication channel is specified in the line configuration, it is connected anyway.
For more details please start a new topic on https://forum.rapidscada.org/?forum=development-and-integration
Support is provided on the forum.
