### ISSUE TITLE
OpenAPI documentation for RapidScada

### ISSUE THREAD

**Issue by mkriachko** [RapidScada/scada-v6#76]
Hello!

Is there any plan to add OpenAPI support, e.g. SwaggerGen & SwaggerUI for documenting and exploring RapidScada and its plugins API?
It would be suitable for integration testing at least.

Best regards,
Mikhail.

**Comment by 2mik** [comment]
Hi Mikhail,
At the moment there is no such plan. It could be done by the community or a 3rd party company.
The existing Web API is available [here](https://github.com/RapidScada/scada-v6/blob/master/ScadaWeb/OpenPlugins/PlgMain/wwwroot/plugins/Main/js/main-api.js)
